set version 21.2R3
set system host-name srx-dc-02
set system services ssh protocol-version v2
set system services ssh root-login deny
set system ntp server 192.0.2.23
set interfaces ge-0/0/2 unit 0 family inet address 192.0.2.137/30
set security zones security-zone trust interfaces ge-0/0/2.0
