set version 20.4R3
set system host-name srx-branch-04
set system services ssh protocol-version v2
set system syslog host 192.0.2.11 any warning
set interfaces ge-0/0/0 unit 0 family inet address 192.0.2.133/30
set security zones security-zone untrust interfaces ge-0/0/0.0
